name: Autograding

on: [push, pull_request]

jobs:
  autograde:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run autograder
        id: autograder
        run: |
          python test_html.py

      - name: Set environment variable for GitHub Actions
        run: |
          # Use jq to format the results.json properly and escape it for GitHub Actions
          echo "AUTOGRADER_RESULTS=$(jq -c . results.json)" >> $GITHUB_ENV

      - name: Report results to GitHub Classroom
        uses: classroom-resources/autograding-grading-reporter@v1
        with:
          runners: autograder
        env:
          AUTOGRADER_RESULTS: ${{ env.AUTOGRADER_RESULTS }}