name: Autograding

on: [push, pull_request]

jobs:
  autograde:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          # Install any dependencies your autograder requires
          pip install -r requirements.txt

      - name: Run autograder
        id: autograder
        run: |
          # Execute your autograding script and capture the output
          python test_html.py
        continue-on-error: true

      - name: Report results to GitHub Classroom
        uses: classroom-resources/autograding-grading-reporter@v1
        with:
          runners: autograder
        env:
          AUTOGRADER_RESULTS: ${{ steps.autograder.outputs.result }}
