name: Autograding

on: [push, pull_request]

jobs:
  autograde:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run autograder
        id: autograder
        run: python test_html.py

      - name: Check JSON encoding
        run: |
          echo "Contents of results.json:"
          cat results.json
          echo "Hexdump of results.json:"
          hexdump -C results.json
          echo "Validating JSON with jq:"
          jq . results.json

      - name: Store results in a file (for GitHub Classroom)
        run: cp results.json autograder_results.json

      - name: Report results to GitHub Classroom
        uses: classroom-resources/autograding-grading-reporter@v1
        with:
          runners: autograder
          results-file: autograder_results.json
