name: Autograding

on: [push, pull_request]

jobs:
  autograde:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          # Install any dependencies your autograder requires
          pip install -r requirements.txt

      - name: Run autograder
        id: autograder
        run: |
          # Execute your autograding script
          python test_html.py

      - name: Encode results as Base64
        id: encode_results
        run: |
          # Ensure results are encoded as Base64 to avoid special character issues
          base64 results.json > results_base64.txt

      - name: Decode results and report to GitHub Classroom
        run: |
          # Decode the Base64-encoded results and save them to a new file
          base64 --decode results_base64.txt > decoded_results.json
          cat decoded_results.json
          
      - name: Report results to GitHub Classroom
        uses: classroom-resources/autograding-grading-reporter@v1
        with:
          runners: autograder
        env:
          # Pass the decoded results file path to the GitHub Classroom reporter
          AUTOGRADER_RESULTS_FILE: ${{ github.workspace }}/decoded_results.json